### ISSUE TITLE
Error on composer update

### ISSUE THREAD

**Issue by Lucasfrota** [fleet-management-and-control/fmc-php-sdk#1]
[Composer\Downloader\TransportException]
  The "http://packagist.org/p/provider-2013%24a0dd7d87825d82d09caf42c529bb02326da2abc38b898b0a60f3ae83b5eedea3.json"
  file could not be downloaded: failed to open stream: Nenhuma conexÒo p¶de ser feita porque a mßquina de destino as
  recusou ativamente.

**Comment by briedis** [comment]
Hmm, strange. This problem looks related to Composer/Packagist it self. Can you try again, maybe on a different network?

I'm able to open the URL in my browser and it works fine.

**Comment by briedis** [comment]
@Lucasfrota any luck?

**Comment by Lucasfrota** [comment]
yes @briedis i tried a different network and it worked properly, thanks for helping :)

**Comment by briedis** [comment]
No problem!

Good luck!
